dist: bionic  # required for Python 3.6
services:
  - xvfb
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
before_install:
  sudo apt-get install -y libgirepository1.0-dev gir1.2-gtk-3.0
install:
  - python setup.py build
  - pip install tox-travis pylint
script:
  - ./bin/check-python-code.sh
  - tox
notifications:
  email: false
